name: CI Pipeline

on:
  push:
    branches: [ "main", "test", "feature/*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate Gradle Wrapper (on CI)
        run: gradle wrapper

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test